In [16]:
!wc -l Data103_format.csv

51 Data103_format.csv

In [12]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.graphics.api as smg
import patsy
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
import seaborn as sns

## 探索数据

In [30]:
df = pd.read_csv("Data103_format.csv", delimiter=",", encoding=None, header=0)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 39 columns):
编号                          16 non-null float64
填写时间                        16 non-null object
姓名                          50 non-null object
GitHub Username             50 non-null object
微信号                         50 non-null object
微信昵称                        27 non-null object
手机                          49 non-null object
E-mail                      50 non-null object
性别                          50 non-null object
sex                         50 non-null int64
所在大区                        47 non-null object
活跃城市                        50 non-null object
目前个人状态                      49 non-null object
status                      50 non-null int64
推荐人                         2 non-null object
你有没有 Python 编码的经历           50 non-null object
python                      50 non-null int64
你有没有其他编程经历？                 50 non-null object
programme                   50 non-null int64
你习惯查阅英文资料吗？                 49 non-null object
english                     50 non-null int64
你用 Google 吗？                50 non-null object
google                      50 non-null int64
你学习数据科学的目的是？                50 non-null object
purpose                     50 non-null int64
你每天的业余自学时间一般多久？             50 non-null object
time                        50 non-null int64
评估自己对于数据库的使用能力              50 non-null object
database                    50 non-null int64
评估自己对于 numpy 的使用能力          50 non-null object
numpy                       50 non-null int64
你最想研究身边的哪种数据？为什么？           50 non-null object
列三本自己看过的数据相关书籍，写一小段感受。      50 non-null object
请用自己的话描述一下统计学中方差的含义。        50 non-null object
请用自己的话描述一下统计学中的回归有什么用。      50 non-null object
请用自己的话描述一下机器学习中决策树的计算步骤。    50 non-null object
score                       50 non-null int64
submit                      50 non-null int64
project                     50 non-null int64
dtypes: float64(1), int64(13), object(25)
memory usage: 15.3+ KB

## 数据预处理

In [32]:
df1 = df.drop(df.columns[[0,1,2,3,4,5,6,7,8,10,11,12,14,15,17,19,21,23,25,27,29,31,32,33,34,35]],axis=1) # 资格审查学员

In [33]:
df1.head()

,sex,status,python,programme,english,google,purpose,time,database,numpy,score,submit,project
0,0,3,1,1,1,2,1,1,0,0,16,9,1
1,1,8,1,1,1,1,1,1,0,0,11,9,1
2,1,5,1,1,2,2,2,1,1,1,14,9,1
3,1,0,0,1,0,1,2,1,1,0,-1,-1,-1
4,1,8,1,0,1,2,1,0,0,0,-1,-1,-1

In [131]:
df2 = df1.ix[df1.project != -1] # 当前学员

In [132]:
df2.head()

,sex,status,python,programme,english,google,purpose,time,database,numpy,score,submit,project
0,0,3,1,1,1,2,1,1,0,0,16,9,1
1,1,8,1,1,1,1,1,1,0,0,11,9,1
2,1,5,1,1,2,2,2,1,1,1,14,9,1
7,0,5,2,2,2,1,2,1,1,0,18,9,0
8,0,5,0,1,2,2,1,1,0,0,2,1,0

## 数据分析

### 分析可能影响平时成绩的因素  

比较显著的是 Google 和 programme。

In [63]:
model11 = smf.ols("score ~ -1 + sex + status + python + programme + english + google + purpose + time + database + numpy", df2)
result11 = model11.fit()
result11.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.665
Model:                            OLS   Adj. R-squared:                  0.542
Method:                 Least Squares   F-statistic:                     5.371
Date:                Sat, 26 Nov 2016   Prob (F-statistic):           0.000232
Time:                        03:03:43   Log-Likelihood:                -108.39
No. Observations:                  37   AIC:                             236.8
Df Residuals:                      27   BIC:                             252.9
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
sex            1.1704      2.115      0.553      0.584        -3.168     5.509
status         0.7096      0.427      1.661      0.108        -0.167     1.586
python         2.2153      1.538      1.440      0.161        -0.941     5.372
programme      3.5262      1.992      1.770      0.088        -0.560     7.613
english        2.4236      1.637      1.480      0.150        -0.936     5.783
google        -3.6731      1.588     -2.313      0.029        -6.932    -0.415
purpose        0.6149      1.222      0.503      0.619        -1.893     3.123
time           1.0583      1.797      0.589      0.561        -2.629     4.746
database      -2.3499      1.986     -1.183      0.247        -6.424     1.724
numpy          0.3058      1.652      0.185      0.854        -3.083     3.695
==============================================================================
Omnibus:                        1.910   Durbin-Watson:                   1.850
Prob(Omnibus):                  0.385   Jarque-Bera (JB):                1.755
Skew:                           0.499   Prob(JB):                        0.416
Kurtosis:                       2.623   Cond. No.                         12.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### 分析可能影响提交作业次数的因素  

比较显著的是个人目前状态。

In [133]:
model21 = smf.ols("submit ~  -1 + sex + status + python + programme + english + google + purpose + time + database + numpy", df2)
result21 = model21.fit()
result21.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 submit   R-squared:                       0.702
Model:                            OLS   Adj. R-squared:                  0.592
Method:                 Least Squares   F-statistic:                     6.361
Date:                Sat, 26 Nov 2016   Prob (F-statistic):           5.90e-05
Time:                        03:24:53   Log-Likelihood:                -91.641
No. Observations:                  37   AIC:                             203.3
Df Residuals:                      27   BIC:                             219.4
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
sex            1.5961      1.345      1.187      0.246        -1.163     4.355
status         0.5824      0.272      2.144      0.041         0.025     1.140
python         1.2243      0.978      1.252      0.221        -0.783     3.232
programme      1.3179      1.267      1.041      0.307        -1.281     3.917
english        1.1189      1.041      1.075      0.292        -1.018     3.255
google        -1.6817      1.010     -1.665      0.107        -3.754     0.390
purpose        0.7049      0.777      0.907      0.372        -0.890     2.300
time           0.4123      1.143      0.361      0.721        -1.932     2.757
database      -1.6087      1.263     -1.274      0.213        -4.199     0.982
numpy          0.2040      1.050      0.194      0.847        -1.951     2.359
==============================================================================
Omnibus:                        1.665   Durbin-Watson:                   1.951
Prob(Omnibus):                  0.435   Jarque-Bera (JB):                1.466
Skew:                           0.350   Prob(JB):                        0.480
Kurtosis:                       2.321   Cond. No.                         12.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### 分析可能影响大作业提交的因素

比较显著的是个人目前状态。

In [54]:
model3 = smf.logit("project ~  -1 + sex + status + python + programme + english + google + purpose + time + database + numpy", 
                   data=df2)
result3 = model3.fit()
result3.summary()

Optimization terminated successfully.
         Current function value: 0.298802
         Iterations 8

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                project   No. Observations:                   37
Model:                          Logit   Df Residuals:                       27
Method:                           MLE   Df Model:                            9
Date:                Sat, 26 Nov 2016   Pseudo R-squ.:                  0.3840
Time:                        02:52:49   Log-Likelihood:                -11.056
converged:                       True   LL-Null:                       -17.947
                                        LLR p-value:                    0.1303
==============================================================================
                 coef    std err          z      P>|z|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
sex           -0.4648      1.365     -0.340      0.734        -3.141     2.212
status         0.6147      0.304      2.021      0.043         0.019     1.211
python        -0.7351      0.979     -0.751      0.453        -2.654     1.184
programme     -0.0802      1.368     -0.059      0.953        -2.762     2.602
english       -0.8363      1.067     -0.784      0.433        -2.928     1.256
google        -2.0479      1.083     -1.892      0.059        -4.170     0.074
purpose        2.1024      1.447      1.453      0.146        -0.734     4.939
time          -1.1947      1.200     -0.996      0.319        -3.546     1.157
database      -1.0183      1.202     -0.847      0.397        -3.374     1.337
numpy          1.6700      1.126      1.483      0.138        -0.538     3.878
==============================================================================
"""